#!/bin/bash

#RTEMS development
export RTEMS_VERSION=5
export RTEMS_ROOT=/home/junkes/MVME3100_REL/rtems/${RTEMS_VERSION}
export RTEMS_ARCH=powerpc-rtems${RTEMS_VERSION}

#git clone https://github.com/RTEMS/rtems-source-builder.git rsb
#cd rsb
#git checkout ${RTEMS_VERSION}
 
#cd rtems
#../source-builder/sb-set-builder \
#  --prefix=${RTEMS_ROOT} \
#  ${RTEMS_VERSION}/rtems-powerpc

#cd ../..

export PATH=${RTEMS_ROOT}/bin:${PATH}

git clone git://git.rtems.org/rtems.git kernel
cd kernel
git checkout ${RTEMS_VERSION}
patch -p1 <../kernel.patch 
./bootstrap -c && ./rtems-bootstrap

cd ..
mkdir -p build/b-mvme3100
cd build/b-mvme3100
../../kernel/configure --prefix=${RTEMS_ROOT} --target=${RTEMS_ARCH} --enable-rtemsbsp=mvme3100 --enable-posix --enable-c++ --enable-networking --enable-tests
make -j14 all
make install

####powerpc-rtems5-objcopy -O binary ./powerpc-rtems5/c/beatnik/testsuites/sptests/spconsole01.exe spconsole01.boot
